linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - bodyclose
    - noctx
    - exhaustive
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
run:
  timeout: 5m
