// Copyright 2026 Penguin Tech Inc
// SPDX-License-Identifier: Apache-2.0

package server

import (
	"context"
	"fmt"

	"buf.build/go/protovalidate"
	"connectrpc.com/connect"
	"google.golang.org/protobuf/proto"
)

// NewValidationInterceptor constructs a protovalidate-go validator once —
// building one compiles the CEL programs behind every buf.validate
// constraint embedded in the proto descriptors this process links, so doing
// it per-request would be needlessly expensive — and returns a
// connect.Interceptor that enforces those constraints against every request
// message at runtime (spec/SPEC.md §5): a unary request, or each message a
// client streams in, is validated before the handler ever sees it. A
// violation is reported as connect.CodeInvalidArgument wrapping the
// protovalidate violation detail; a message type with no buf.validate
// constraints (for example prpc.health.v1.CheckRequest) validates trivially.
func NewValidationInterceptor() (connect.Interceptor, error) {
	validator, err := protovalidate.New()
	if err != nil {
		return nil, fmt.Errorf("server: constructing protovalidate validator: %w", err)
	}
	return &validationInterceptor{validator: validator}, nil
}

// validationInterceptor is a full connect.Interceptor rather than a
// connect.UnaryInterceptorFunc: connect.UnaryInterceptorFunc's
// WrapStreamingHandler is a documented no-op (connectrpc.com/connect
// v1.20.0, interceptor.go lines 70-73 — the same lesson this repo's auth
// chain, ../auth/auth.go, already had to work around), so it would silently
// skip validating every message a client streams in. WrapStreamingHandler
// below instead wraps the connect.StreamingHandlerConn so every
// successfully decoded message — unary or one of many in a stream — passes
// through validateMessage before the handler observes it.
type validationInterceptor struct {
	validator protovalidate.Validator
}

// WrapUnary validates the request message before invoking next. A violation
// short-circuits the call — next is never invoked — and the caller receives
// connect.CodeInvalidArgument.
func (i *validationInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
		if err := i.validateMessage(req.Any()); err != nil {
			return nil, err
		}
		return next(ctx, req)
	}
}

// WrapStreamingClient is a pass-through: this interceptor only enforces
// constraints on messages a server receives, so it has no client-side role.
func (i *validationInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
	return next
}

// WrapStreamingHandler wraps conn so every message the handler receives —
// via conn.Receive directly, or through the generated *connect.ClientStream
// / *connect.BidiStream helpers, which delegate to it — is validated
// immediately after it is decoded. The first violation terminates the
// stream: Receive returns the CodeInvalidArgument error in place of a
// decoded message, which every handler generated by this repo's stubs
// surfaces as the RPC's terminal error without processing any further
// messages.
func (i *validationInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
	return func(ctx context.Context, conn connect.StreamingHandlerConn) error {
		return next(ctx, &validatingStreamingHandlerConn{StreamingHandlerConn: conn, interceptor: i})
	}
}

// validateMessage runs msg through i.validator when msg is a proto.Message,
// translating any violation into a connect.CodeInvalidArgument error carrying
// the protovalidate violation detail as its cause. A msg that is not a
// proto.Message passes through untouched — every request this repo's
// generated stubs produce is a proto.Message, but the type assertion guards
// rather than assumes that, so a non-proto message (which connect never
// actually constructs here) cannot panic this interceptor.
func (i *validationInterceptor) validateMessage(msg any) error {
	pm, ok := msg.(proto.Message)
	if !ok {
		return nil
	}
	if err := i.validator.Validate(pm); err != nil {
		return connect.NewError(connect.CodeInvalidArgument, err)
	}
	return nil
}

// validatingStreamingHandlerConn wraps a connect.StreamingHandlerConn so
// every message Receive decodes is validated before its caller — the
// generated *connect.ClientStream / *connect.BidiStream helper, or a
// handler calling Receive directly — observes it.
type validatingStreamingHandlerConn struct {
	connect.StreamingHandlerConn
	interceptor *validationInterceptor
}

// Receive decodes into msg via the embedded conn, then validates msg before
// returning. msg has already been fully decoded by the time a violation is
// found, but Receive returns the violation error in place of a nil error, so
// callers (per the connect.StreamingHandlerConn.Receive contract) must treat
// the call as failed and stop reading — every generated handler in this
// repo does exactly that.
func (c *validatingStreamingHandlerConn) Receive(msg any) error {
	if err := c.StreamingHandlerConn.Receive(msg); err != nil {
		return err
	}
	return c.interceptor.validateMessage(msg)
}
